name: 'sample-action'
description: 'A sample action.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1
    - run: |
        v="${{ github.action_ref }}"
        v=$(echo "${v:1}")
        echo "::set-output name=version::$v"
      shell: bash
    - run: |
        echo The version of this action is "${{ github.action_ref }}"
      shell: bash
