name: test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ github.ref_type }}"
    - uses: ./
